services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env.docker
    restart: unless-stopped
    networks:
      - backend

  mongo:
    image: mongo:8
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - backend

volumes:
  mongo-data:

networks:
  backend:
