openapi: 3.1.0
info:
  title: CycleAPI
  description: A simple API to manage books.
  version: "1.0.0"

paths:
  /products:
    get:
      summary: Get all products
      responses:
        200:
          description: List of products.
      tags:
        - Products
    post:
      summary: Create a new product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                category:
                  type: string
                launchDate:
                  type: string
                  format: date
                price:
                  type: number
      responses:
        201:
          description: Product created.
      tags:
        - Products

  /products/{id}:
    get:
      summary: Get a product by ID
      responses:
        200:
          description: Product returned.
        404:
          description: Product not found.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product
      tags:
        - Products

    delete:
      summary: Delete a product
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the product
      responses:
        201:
          description: Product is deleted.
      tags:
        - Products

  /products/{productId}/sales/{interval}:
    get:
      summary: Get the sales of a product by ID
      responses:
        200:
          description: Sales returned.
        404:
          description: No sale found.
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: The ID of the product
        - in: path
          name: interval
          required: true
          schema:
            type: string
          description: Interval of the sales
      tags:
        - Sales

  /products/{productId}/sales:
    post:
      summary: Create a new sale
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                amount:
                  type: number
                  default: 1
                customPrice:
                  type: number
                  required: false
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: The ID of the product
      responses:
        201:
          description: New sale added.
      tags:
        - Sales

  /products/{productId}/sales/restore:
    put:
      summary: Restore old sales.
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: The ID of the product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  _id:
                    required: false
                    type: string
                  amount:
                    required: true
                    type: number
                    description: Quanitity of the sale.
                  customPrice:
                    required: false
                    type: number
                  createdAt:
                    required: true
                    type: date
                    description: Date and time of the sale.
                  updatedAt:
                    required: true
                    type: date
                    description: Date and time of the last update of the sale.
      responses:
        200:
          description: Sales are restored.
      tags:
        - Sales
  /products/{productId}/sales/{saleId}:
    delete:
      summary: Delete a sale
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: The ID of the product
        - in: path
          name: saleId
          required: true
          schema:
            type: string
          description: The ID of the sale
      responses:
        201:
          description: Sale is deleted.
      tags:
        - Sales
  /lifecycle/{productId}/moving-averages:
    post:
      summary: Get the moving averages of sales of a product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: The ID of the product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                windowSize:
                  type: number
                weight:
                  type: boolean
                interval:
                  type: string
      responses:
        201:
          description: Moving averages are listed.
      tags:
        - Lifecycle
  /lifecycle/{productId}/growth-rates:
    post:
      summary: Get the growth rates of a product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: The ID of the product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                interval:
                  type: string
      responses:
        201:
          description: Growth rates are listed.
      tags:
        - Lifecycle
  /lifecycle/{productId}/acceleration-rates:
    post:
      summary: Get the acceleration rates of a product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: The ID of the product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                interval:
                  type: string
      responses:
        201:
          description: Acceleration rates are listed.
      tags:
        - Lifecycle
  /lifecycle/{productId}/lr-slopes:
    post:
      summary: Get the linear regression of sales of a product
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
          description: The ID of the product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                windowSize:
                  type: number
                interval:
                  type: string
      responses:
        201:
          description: Linear regression slopes are listed.
      tags:
        - Lifecycle
